### ISSUE TITLE
Latex compilation error

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/latex-template#98]
Hello compiling a tutorial, I have this error : 

```

)

(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty

Package: ltxcmds 2016/05/16 v1.23 LaTeX kernel commands for general use (HO)

)

\Gread@gobject=\count125

)

(/usr/share/texlive/texmf-dist/tex/latex/colortbl/colortbl.sty

Package: colortbl 2012/02/13 v1.0a Color table columns (DPC)



(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty

Package: array 2016/10/06 v2.4d Tabular extension package (FMi)

\col@sep=\dimen137

\extrarowheight=\dimen138

\NC@list=\toks15

\extratabsurround=\skip62

\backup@length=\skip63

)

\everycr=\toks16

\minrowclearance=\skip64

)

\rownum=\count126

Package xcolor Info: Model `cmy' substituted by `cmy0' on input line 1348.

Package xcolor Info: Model `hsb' substituted by `rgb' on input line 1352.

Package xcolor Info: Model `RGB' extended on input line 1364.

. Defining environment 'Error' with sig. ' o ' on line 331.

.................................................

.................................................

. LaTeX info: "xparse/define-environment"

. 

. Defining environment 'Neutral' with sig. ' o ' on line 332.

.................................................

.................................................

. LaTeX info: "xparse/define-environment"

. 

. Defining environment 'Quotation' with sig. ' o ' on line 342.

.................................................

.................................................

. LaTeX info: "xparse/define-environment"

. 

. Defining environment 'CodeBlock' with sig. 'O{}O{}O{1}m' on line 379.

.................................................

.................................................

. LaTeX info: "xparse/define-command"

. 

. Defining command \CodeInline with sig. 'm' on line 391.

.................................................

.................................................

. LaTeX info: "xparse/define-command"

. 

! error:  (file /opt/zds/data/contents-public/reprenez-le-controle-de-vos-feuill

es-de-style-avec-sass__building/extra_contents/images/t5KXGlIzPI/8UiZ_7891N1.png

) (pdf backend): internal error: unknown image type

!  ==> Fatal error occurred, no output PDF file produced! ext=.pdf
ERROR:ZMarkdownRebberLatexPublicator:could not publish /opt/zds/data/contents-public/reprenez-le-controle-de-vos-feuilles-de-style-avec-sass__building/extra_contents/reprenez-le-controle-de-vos-feuilles-de-style-avec-sass.pdf
Traceback (most recent call last):
  File "/opt/zds/app/zds/tutorialv2/publication_utils.py", line 419, in publish
    self.full_tex_compiler_call(latex_file_path)
  File "/opt/zds/app/zds/tutorialv2/publication_utils.py", line 434, in full_tex_compiler_call
    handle_tex_compiler_error(latex_file, self.extension)
  File "/opt/zds/app/zds/tutorialv2/publication_utils.py", line 499, in handle_tex_compiler_error
    raise FailureDuringPublication(errors)
zds.tutorialv2.publication_utils.FailureDuringPublication: Package: infwarerr 2016/05/16 v1.4 Providing info/warning/error messages (HO)

)

(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty

Package: ltxcmds 2016/05/16 v1.23 LaTeX kernel commands for general use (HO)

)

\Gread@gobject=\count125

)

(/usr/share/texlive/texmf-dist/tex/latex/colortbl/colortbl.sty

Package: colortbl 2012/02/13 v1.0a Color table columns (DPC)



(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty

Package: array 2016/10/06 v2.4d Tabular extension package (FMi)

\col@sep=\dimen137

\extrarowheight=\dimen138

\NC@list=\toks15

\extratabsurround=\skip62

\backup@length=\skip63

)

\everycr=\toks16

\minrowclearance=\skip64

)

\rownum=\count126

Package xcolor Info: Model `cmy' substituted by `cmy0' on input line 1348.

Package xcolor Info: Model `hsb' substituted by `rgb' on input line 1352.

Package xcolor Info: Model `RGB' extended on input line 1364.

. Defining environment 'Error' with sig. ' o ' on line 331.

.................................................

.................................................

. LaTeX info: "xparse/define-environment"

. 

. Defining environment 'Neutral' with sig. ' o ' on line 332.

.................................................

.................................................

. LaTeX info: "xparse/define-environment"

. 

. Defining environment 'Quotation' with sig. ' o ' on line 342.

.................................................

.................................................

. LaTeX info: "xparse/define-environment"

. 

. Defining environment 'CodeBlock' with sig. 'O{}O{}O{1}m' on line 379.

.................................................

.................................................

. LaTeX info: "xparse/define-command"

. 

. Defining command \CodeInline with sig. 'm' on line 391.

.................................................

.................................................

. LaTeX info: "xparse/define-command"

. 

! error:  (file /opt/zds/data/contents-public/reprenez-le-controle-de-vos-feuill

es-de-style-avec-sass__building/extra_contents/images/t5KXGlIzPI/8UiZ_7891N1.png

) (pdf backend): internal error: unknown image type

!  ==> Fatal error occurred, no output PDF file produced!
- reprenez-le-controle-de-vos-feuilles-de-style-avec-sass [ERREUR]
```

- latex is https://beta.zestedesavoir.com/tutoriels/tex/672/reprenez-le-controle-de-vos-feuilles-de-style-avec-sass.tex
- mardkown is https://beta.zestedesavoir.com/tutoriels/md/672/reprenez-le-controle-de-vos-feuilles-de-style-avec-sass.md

**Comment by pierre-24** [comment]
Seems that there is an issue with an image. Which one is `images/t5KXGlIzPI/8UiZ_7891N1.png`, if it is possible for you to see it?

**Comment by artragis** [comment]
![8uiz_7891n1](https://user-images.githubusercontent.com/1523653/47487124-254c5200-d842-11e8-9d61-5e3b42746a07.png)

**Comment by pierre-24** [comment]
Ok. I'm pretty sure that it is then a rebber/zds-site related "error" : a webserver use HTTP 200 instead of HTTP 404 :o
